services:
  app:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python manage.py wait_for_db
             python manage.py migrate
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
