# Generated by Django 4.2.11 on 2024-05-06 14:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_id_alter_orderitem_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=core.models.image_file_path),
            preserve_default=False,
        ),
    ]
